version: '3.9'

volumes:
  node_modules_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules

services:
  bitcoin-nostred-auction-dev:
    image: bitcoin-nostred-auction-dev
    container_name: bitcoin-nostred-auction-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /bitcoin-nostred-auction
    ports:
      - "9229:9229"
      - "4200:4200"
    volumes:
      - ..:/bitcoin-nostred-auction:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - node_modules_vol:/bitcoin-nostred-auction/node_modules
    tty: true
